ALTER TABLE PhuHuynh
ADD CONSTRAINT FK_PhuHuynh_NguoiDung
FOREIGN KEY (CCCD) REFERENCES NguoiDung(CCCD);

ALTER TABLE GiaSu
ADD CONSTRAINT FK_GiaSu_NguoiDung
FOREIGN KEY (CCCD) REFERENCES NguoiDung(CCCD);

ALTER TABLE DonTuyenGiaSu
ADD CONSTRAINT FK_DonTuyenGiaSu_PhuHuynh
FOREIGN KEY (CCCD) REFERENCES PhuHuynh(CCCD);

ALTER TABLE DonDangKyLamGiaSu
ADD CONSTRAINT FK_DonDangKyLamGiaSu_GiaSu
FOREIGN KEY (CCCD) REFERENCES GiaSU(CCCD);

ALTER TABLE CV
ADD CONSTRAINT FK_CV_GiaSu
FOREIGN KEY (CCCD) REFERENCES GiaSu(CCCD);

ALTER TABLE CV_BangCap
ADD CONSTRAINT FK_BangCap_CV
FOREIGN KEY (CV_ID) REFERENCES CV(CV_ID);

ALTER TABLE CV_KinhNghiem
ADD CONSTRAINT FK_KinhNghiem_CV
FOREIGN KEY (CV_ID) REFERENCES CV(CV_ID);

ALTER TABLE GiaSu_CO_LopHoc
ADD CONSTRAINT FK_GiaSu_CO_LopHoc_GiaSu
FOREIGN KEY (CCCD) REFERENCES GiaSu(CCCD),
ADD CONSTRAINT FK_GiaSu_CO_LopHoc_LopHoc
FOREIGN KEY (ID_Lophoc) REFERENCES LopHoc(ID);

ALTER TABLE PhuHuynh_CO_LopHoc
ADD CONSTRAINT FK_PhuHuynh_CO_LopHoc_PhuHuynh
FOREIGN KEY (CCCD) REFERENCES PhuHuynh(CCCD),
ADD CONSTRAINT FK_PhuHuynh_CO_LopHoc_LopHoc
FOREIGN KEY (ID_Lophoc) REFERENCES LopHoc(ID);

ALTER TABLE LopHoc
ADD CONSTRAINT FK_LopHoc_MonHoc
FOREIGN KEY (ID_MonHoc) REFERENCES MonHoc(ID);


ALTER TABLE TaiKhoanAdmin
ADD CONSTRAINT FK_TaiKhoanAdmin_TaiKhoan
FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoan(TenDangNhap);

ALTER TABLE TaiKhoanPhuHuynh
ADD CONSTRAINT FK_TaiKhoanPhuHuynh_PhuHuynh
FOREIGN KEY (CCCD) REFERENCES PhuHuynh(CCCD),
ADD CONSTRAINT FK_TaiKhoanPhuHuynh_TaiKhoanNguoiDung
FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoanNguoiDung(TenDangNhap);

ALTER TABLE TaiKhoanGiaSu
ADD CONSTRAINT FK_TaiKhoanGiaSu_GiaSu
FOREIGN KEY (CCCD) REFERENCES GiaSu(CCCD),
ADD CONSTRAINT FK_TaiKhoanGiaSu_TaiKhoanNguoiDung
FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoanNguoiDung(TenDangNhap);

ALTER TABLE DanhGia
ADD CONSTRAINT FK_DanhGia_TaiKhoanGiaSu
FOREIGN KEY (TenDangNhap) REFERENCES TaiKhoanGiaSu(TenDangNhap);

ALTER TABLE TinNhan
ADD CONSTRAINT FK_TinNhan_TaiKhoan_NguoiGui
FOREIGN KEY (NguoiGui) REFERENCES TaiKhoan(TenDangNhap),
ADD CONSTRAINT FK_TinNhan_TaiKhoan_NguoiNhan					
FOREIGN KEY (NguoiNhan) REFERENCES TaiKhoan(TenDangNhap);
